-- H2 2.4.240;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'cb10f6e81d0d0900' HASH '1454e23ec3e3b8917fbc34139016eb137f8340548bd77fd0dda8c58ee43187d6' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."CLIENTES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "NOMBRES" CHARACTER VARYING(255) NOT NULL,
    "APELLIDOS" CHARACTER VARYING(255) NOT NULL,
    "FECHA_NACIMIENTO" DATE NOT NULL,
    "NUMERO_IDENTIFICACION" CHARACTER VARYING(255) NOT NULL,
    "TIPO_IDENTIFICACION" CHARACTER VARYING(100) NOT NULL,
    "CIUDAD" CHARACTER VARYING(100) NOT NULL,
    "DEPARTAMENTO" CHARACTER VARYING(100) NOT NULL,
    "PAIS" CHARACTER VARYING(100) NOT NULL,
    "DIRECCION" CHARACTER VARYING(255) NOT NULL,
    "MARCA" CHARACTER VARYING(100) NOT NULL
);      
ALTER TABLE "PUBLIC"."CLIENTES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.CLIENTES;
INSERT INTO "PUBLIC"."CLIENTES" VALUES
(1, 'stiven', 'gil', DATE '2022-05-08', '33456', U&'C\00e9dula de Ciudadan\00eda', 'Monterrey', U&'Nuevo Le\00f3n', U&'M\00e9xico', 'ghf', 'Chevignon'),
(2, 'pp', 'hh', DATE '2022-02-01', '1214744811', U&'C\00e9dula de Ciudadan\00eda', 'La Plata', 'Buenos Aires', 'Argentina', 'cra 33 *98', 'Americanino'),
(4, 'stiven', 'gil', DATE '2024-01-30', '3345634', U&'C\00e9dula de Extranjer\00eda', 'Guadalajara', 'Jalisco', U&'M\00e9xico', 'cra 33 *98nn', 'Esprit'),
(5, 'df', 'ee', DATE '2023-01-30', '33456444', 'Pasaporte', U&'M\00e1laga', U&'Andaluc\00eda', U&'Espa\00f1a', 'cra 33 *98nn', 'American Eagle');    
CREATE MEMORY TABLE "PUBLIC"."PAISES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NOMBRE" CHARACTER VARYING(100) NOT NULL
);            
ALTER TABLE "PUBLIC"."PAISES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.PAISES;  
INSERT INTO "PUBLIC"."PAISES" VALUES
(1, 'Colombia'),
(2, U&'M\00e9xico'),
(3, 'Argentina'),
(4, U&'Espa\00f1a');         
CREATE MEMORY TABLE "PUBLIC"."DEPARTAMENTOS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NOMBRE" CHARACTER VARYING(100) NOT NULL,
    "PAIS_ID" BIGINT NOT NULL
);     
ALTER TABLE "PUBLIC"."DEPARTAMENTOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_85" PRIMARY KEY("ID");               
-- 45 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTAMENTOS;          
INSERT INTO "PUBLIC"."DEPARTAMENTOS" VALUES
(1, 'Amazonas', 1),
(2, 'Antioquia', 1),
(3, 'Arauca', 1),
(4, U&'Atl\00e1ntico', 1),
(5, U&'Bogot\00e1 D.C.', 1),
(6, U&'Bol\00edvar', 1),
(7, U&'Boyac\00e1', 1),
(8, 'Caldas', 1),
(9, U&'Caquet\00e1', 1),
(10, 'Casanare', 1),
(11, 'Cauca', 1),
(12, 'Cesar', 1),
(13, U&'Choc\00f3', 1),
(14, U&'C\00f3rdoba', 1),
(15, 'Cundinamarca', 1),
(16, U&'Guain\00eda', 1),
(17, 'Guaviare', 1),
(18, 'Huila', 1),
(19, 'La Guajira', 1),
(20, 'Magdalena', 1),
(21, 'Meta', 1),
(22, U&'Nari\00f1o', 1),
(23, 'Norte de Santander', 1),
(24, 'Putumayo', 1),
(25, U&'Quind\00edo', 1),
(26, 'Risaralda', 1),
(27, U&'San Andr\00e9s y Providencia', 1),
(28, 'Santander', 1),
(29, 'Sucre', 1),
(30, 'Tolima', 1),
(31, 'Valle del Cauca', 1),
(32, U&'Vaup\00e9s', 1),
(33, 'Vichada', 1),
(34, 'Jalisco', 2),
(35, U&'Nuevo Le\00f3n', 2),
(36, U&'Ciudad de M\00e9xico', 2),
(37, 'Quintana Roo', 2),
(38, 'Buenos Aires', 3),
(39, U&'C\00f3rdoba', 3),
(40, 'Mendoza', 3),
(41, 'Santa Fe', 3),
(42, 'Madrid', 4),
(43, U&'Catalu\00f1a', 4),
(44, U&'Andaluc\00eda', 4),
(45, 'Comunidad Valenciana', 4);    
CREATE MEMORY TABLE "PUBLIC"."CIUDADES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NOMBRE" CHARACTER VARYING(100) NOT NULL,
    "DEPARTAMENTO_ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."CIUDADES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");     
-- 70 +/- SELECT COUNT(*) FROM PUBLIC.CIUDADES;               
INSERT INTO "PUBLIC"."CIUDADES" VALUES
(1, 'Leticia', 1),
(2, U&'Medell\00edn', 2),
(3, 'Envigado', 2),
(4, 'Bello', 2),
(5, U&'Itag\00fc\00ed', 2),
(6, 'Rionegro', 2),
(7, 'Arauca', 3),
(8, 'Barranquilla', 4),
(9, 'Soledad', 4),
(10, U&'Bogot\00e1', 5),
(11, 'Cartagena', 6),
(12, 'Tunja', 7),
(13, 'Duitama', 7),
(14, 'Sogamoso', 7),
(15, 'Manizales', 8),
(16, 'Florencia', 9),
(17, 'Yopal', 10),
(18, U&'Popay\00e1n', 11),
(19, 'Valledupar', 12),
(20, U&'Quibd\00f3', 13),
(21, U&'Monter\00eda', 14),
(22, 'Soacha', 15),
(23, 'Girardot', 15),
(24, U&'Zipaquir\00e1', 15),
(25, U&'In\00edrida', 16),
(26, U&'San Jos\00e9 del Guaviare', 17),
(27, 'Neiva', 18),
(28, 'Riohacha', 19),
(29, 'Santa Marta', 20),
(30, 'Villavicencio', 21),
(31, 'Pasto', 22),
(32, U&'C\00facuta', 23),
(33, 'Mocoa', 24),
(34, 'Armenia', 25),
(35, 'Pereira', 26),
(36, U&'San Andr\00e9s', 27),
(37, 'Bucaramanga', 28),
(38, 'Floridablanca', 28),
(39, 'Sincelejo', 29),
(40, U&'Ibagu\00e9', 30),
(41, 'Cali', 31),
(42, 'Palmira', 31),
(43, 'Buenaventura', 31),
(44, U&'Mit\00fa', 32),
(45, U&'Puerto Carre\00f1o', 33),
(46, 'Guadalajara', 34),
(47, 'Zapopan', 34),
(48, 'Monterrey', 35),
(49, U&'San Pedro Garza Garc\00eda', 35),
(50, U&'Ciudad de M\00e9xico', 36),
(51, U&'Canc\00fan', 37),
(52, 'Playa del Carmen', 37),
(53, 'Buenos Aires', 38),
(54, 'La Plata', 38),
(55, 'Mar del Plata', 38),
(56, U&'C\00f3rdoba', 39),
(57, 'Villa Carlos Paz', 39),
(58, 'Mendoza', 40),
(59, 'San Rafael', 40),
(60, 'Rosario', 41),
(61, 'Santa Fe', 41),
(62, 'Madrid', 42),
(63, U&'Alcal\00e1 de Henares', 42),
(64, 'Barcelona', 43),
(65, 'Girona', 43),
(66, 'Sevilla', 44),
(67, U&'M\00e1laga', 44),
(68, 'Granada', 44),
(69, 'Valencia', 45),
(70, 'Alicante', 45);      
CREATE MEMORY TABLE "PUBLIC"."MARCAS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NOMBRE" CHARACTER VARYING(50) NOT NULL
);             
ALTER TABLE "PUBLIC"."MARCAS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87" PRIMARY KEY("ID");      
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.MARCAS;  
INSERT INTO "PUBLIC"."MARCAS" VALUES
(1, 'Americanino'),
(2, 'American Eagle'),
(3, 'Chevignon'),
(4, 'Esprit'),
(5, 'Naf Naf'),
(6, 'Rifle');          
CREATE MEMORY TABLE "PUBLIC"."TIPOS_IDENTIFICACION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NOMBRE" CHARACTER VARYING(50) NOT NULL
);               
ALTER TABLE "PUBLIC"."TIPOS_IDENTIFICACION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TIPOS_IDENTIFICACION;    
INSERT INTO "PUBLIC"."TIPOS_IDENTIFICACION" VALUES
(1, U&'C\00e9dula de Ciudadan\00eda'),
(2, U&'C\00e9dula de Extranjer\00eda'),
(3, 'Pasaporte');        
ALTER TABLE "PUBLIC"."CLIENTES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_64" UNIQUE NULLS DISTINCT ("NUMERO_IDENTIFICACION");      
ALTER TABLE "PUBLIC"."MARCAS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_871" UNIQUE NULLS DISTINCT ("NOMBRE");      
