spring.application.name=fidelidad


spring.datasource.url=jdbc:h2:mem:fidelidaddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always