CREATE TABLE clientes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres                 VARCHAR(255) NOT NULL,
    apellidos               VARCHAR(255) NOT NULL,
    fecha_nacimiento        DATE NOT NULL,
    numero_identificacion   VARCHAR(255) NOT NULL UNIQUE,
    tipo_identificacion     VARCHAR(100) NOT NULL,
    ciudad                  VARCHAR(100) NOT NULL,
    departamento            VARCHAR(100) NOT NULL,
    pais                    VARCHAR(100) NOT NULL,
    direccion               VARCHAR(255) NOT NULL,
    marca                   VARCHAR(100) NOT NULL
);

CREATE TABLE paises (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(100) NOT NULL
);

CREATE TABLE departamentos (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(100) NOT NULL,
    pais_id   BIGINT NOT NULL
);

CREATE TABLE ciudades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    departamento_id BIGINT NOT NULL
);

CREATE TABLE marcas (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tipos_identificacion (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(50) NOT NULL
);
